# Topic 0.1 — NumPy vectors & matrices (LESSON)

Read each section, **run every cell**, and match the output to the code.
Then go earn your checkmarks in `drills.ipynb`.

**Why this topic exists:** in ML, *everything* is a vector or a matrix —
- one data sample → a vector of features, shape `(n_features,)`
- a whole dataset → a matrix, one row per sample, shape `(n_samples, n_features)`
- model weights → a vector (or matrix)

In [1]:
import time
import numpy as np

rng = np.random.default_rng(seed=42)

## 1. A vector is just an array with a shape

In [2]:
v = np.array([2.0, -1.0, 3.0])
M = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])

print(f"v       = {v},  shape={v.shape}")   # (3,)   1-D: a vector
print(f"M shape = {M.shape}")               # (2, 3) 2-D: a matrix

v       = [ 2. -1.  3.],  shape=(3,)
M shape = (2, 3)


## 2. The dot product — the single most-used operation in ML

Multiply elementwise, then sum. That's it.

Why care? A linear model's prediction **is** a dot product: `prediction = weights · features + bias`

In [3]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([4.0, 5.0, 6.0])

manual = 0.0
for i in range(len(a)):
    manual += a[i] * b[i]

print(f"by loop : {manual}")            # 1*4 + 2*5 + 3*6 = 32
print(f"np.dot  : {np.dot(a, b)}")
print(f"a @ b   : {a @ b}   (@ is the same thing)")

by loop : 32.0
np.dot  : 32.0
a @ b   : 32.0   (@ is the same thing)


## 3. Why we vectorize: loops are slow, NumPy is fast

This is THE reason ML code looks the way it does: no loops over samples, ever.
One matrix expression handles the whole dataset at once.

In [4]:
big_a = rng.random(1_000_000)
big_b = rng.random(1_000_000)

t0 = time.perf_counter()
s = 0.0
for i in range(len(big_a)):
    s += big_a[i] * big_b[i]
loop_ms = (time.perf_counter() - t0) * 1000

t0 = time.perf_counter()
s2 = big_a @ big_b
numpy_ms = (time.perf_counter() - t0) * 1000

print(f"python loop: {loop_ms:8.1f} ms")
print(f"numpy @    : {numpy_ms:8.2f} ms   -> ~{loop_ms / numpy_ms:.0f}x faster")

python loop:    550.4 ms
numpy @    :     5.13 ms   -> ~107x faster


## 4. Matrix multiplication = many dot products at once

**The shape rule:** `(a, b) @ (b, c) -> (a, c)`. Inner dims must MATCH.

ML translation: `X (100 samples, 3 features) @ w (3 weights) -> 100 predictions` in ONE line — that's section 3's speedup applied to a whole model.

In [5]:
# (2,3) @ (3,) -> (2,)  : each ROW of M dotted with v
print(f"M @ v = {M @ v}")
print(f"  row0 . v = {M[0] @ v},  row1 . v = {M[1] @ v}  (same numbers!)")

A = rng.random((4, 3))
B = rng.random((3, 5))
print(f"(4,3) @ (3,5) -> {(A @ B).shape}")

M @ v = [ 9. 21.]
  row0 . v = 9.0,  row1 . v = 21.0  (same numbers!)
(4,3) @ (3,5) -> (4, 5)


## 5. Broadcasting — NumPy stretches shapes for you

**The rule:** compare shapes right-to-left; dims are compatible if **equal or 1**.

```
(3, 2) vs (2,)  -> (2,) acts like (1, 2) -> stretched to (3, 2). OK!
(3, 2) vs (3,)  -> ERROR: 2 vs 3 mismatch on the last axis.
```

**Gotcha:** to broadcast per-ROW you need a *column* shape `(3, 1)` — that's what `keepdims=True` is for.

In [6]:
X = np.array([[1.0, 2.0],
              [3.0, 4.0],
              [5.0, 6.0]])          # (3, 2): 3 samples, 2 features

print(f"X * 10 :\n{X * 10}")         # scalar stretches to every element

col_means = X.mean(axis=0)           # (2,) — mean of each COLUMN (axis 0 collapses rows)
print(f"col_means = {col_means}")
print(f"X - col_means :\n{X - col_means}")   # this one line CENTERS a dataset!

row_sums = X.sum(axis=1, keepdims=True)      # (3, 1) instead of (3,)
print(f"X / row_sums (normalize each row):\n{X / row_sums}")

X * 10 :
[[10. 20.]
 [30. 40.]
 [50. 60.]]
col_means = [3. 4.]
X - col_means :
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
X / row_sums (normalize each row):
[[0.33333333 0.66666667]
 [0.42857143 0.57142857]
 [0.45454545 0.54545455]]


---
**Lesson done.** Now open `drills.ipynb` and make every check pass. ✅